In [5]:
import numpy as np
import pandas as pd

In [6]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns= ['cgpa','profile_score','lpa'])

In [7]:
df.head()

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [8]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [9]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
model.get_weights()

[array([[ 1.2010344 , -0.59451306],
        [ 0.0284754 , -0.13977456]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.39560485],
        [-0.04141653]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype=float32),
               np.array([0.,0.],dtype=float32),
              np.array([[0.1],[0.1]],dtype=float32),
               np.array([0.],dtype=float32)]

NameError: name 'float32' is not defined